### ISSUE TITLE
Which version(s) of Flex Radio firmware are targeted?

### ISSUE THREAD

**Issue by hightowe** [kc2g-flex-tools/nCAT#10]
Hi guys,

I am getting stuck "Looking for slice slice_id=A" and am curious if maybe the firmware version of the radio (2.4.9) may be a problem:

```
root@raspberrypi:/home/pi/nCAT# ./nCAT-linux-arm -headless -radio 192.168.55.233 -log-level debug
6:35PM INF Registering client
6:35PM INF Got client handle handle=0x535089B2
6:35PM INF Looking for slice slice_id=A
```

Tracing the tcp connection with tcpdump, communication seems to just stop at the "looking for slice" point.

Also, is debug the highest log level?

Thanks!
Lester

**Comment by arodland** [comment]
Only firmware 3.x is targeted.

The highest log level is "trace", one step above "debug", which includes all requests and responses on the hamlib port.

**Comment by hightowe** [comment]
Thank you!
