### ISSUE TITLE
rigctl issue

### ISSUE THREAD

**Issue by iz4tow** [kc2g-flex-tools/nCAT#13]
Hi,
I'm using nCAT with this command
_sudo ./nCAT -listen 127.0.0.1:4532 -headless_ 

and RIGCTL to read freq with this command:
igctl -m 2 -r 127.0.0.1:4532 f

this is the output of nCAT:
5:37PM INF Registering client
5:37PM INF Got client handle handle=0x466A2ADF
5:37PM INF Looking for slice slice_id=A
5:37PM INF Found slice slice_idx=0
5:38PM WRN Handler returned error error="no such VFO VFOB" cmd=["V","VFOB"]
5:38PM WRN No handler found cmd=["\\get_powerstat"]

and this is the output of rigctl:
get_freq: error =   2:rig_get_mode: elapsed=1ms
  2:rig.c(2479):rig_get_mode returning(0) 
 1:rig.c(1361):rig_open returning(0) 
main vfo_opt=0
Backend version: 20220722.0, Status: Stable
rigctl_parse: called, interactive=0
rigctl_parse: vfo_opt=0
rigctl_parse: rig_powerstat is not on = 0
 1:rig.c(5848):rig_get_powerstat entered
rig.c(5866) trace
netrigctl_get_powerstat called
netrigctl_transaction: called len=15
rig_flush: called for network device
network_flush called
write_block(): TX 15 bytes, method=2
read_string_generic called, rxmax=1024 direct=1, expected_len=1
read_string_generic(): RX 7 characters, direct=1
 1:rig.c(5868):rig_get_powerstat returning(0) 
rigctl_parse: command get_freq not allowed when rig is powered off
Rig is not powered on

nCAT version: v0.1-20221007.1
hamlib version: rigctl Hamlib 4.6~git Mon Nov 07 18:24:55 2022 +0000 SHA=0963d8

**Comment by arodland** [comment]
Looks like they added something new in hamlib again, and made the client compatible with older servers, again. I'll look into it and try to get a fix soon. Meanwhile, I think that things should work fine with hamlib / rigctl version 4.5.

**Comment by iz4tow** [comment]
Yes that's correct...I'm trying with an old version of rifctl and it works.
Please let me know when you'll correct 
Thanks

**Comment by arodland** [comment]
Please check if https://github.com/kc2g-flex-tools/nCAT/releases/tag/v0.1-20221109.0 fixes it for you.

**Comment by iz4tow** [comment]
Yes it seems to work. Thanks

**Comment by iz4tow** [comment]
Mmmm. Some issues remains. Not all commands are working well.

**Comment by iz4tow** [comment]
Here the log when I try to switch from LSB/USB

6:48PM WRN No handler found cmd=["\\get_lock_mode"]
6:48PM WRN Handler returned error error="no such VFO VFOB" cmd=["V","VFOB"]
6:48PM WRN Handler returned error error="no such VFO VFOB" cmd=["V","VFOB"]
6:48PM WRN Handler returned error error="no such VFO VFOB" cmd=["V","VFOB"]


The command on rigctl is:
rigctl -m 2 -r 127.0.0.1:4532 M USB 3000

**Comment by arodland** [comment]
That should all be harmless, although I don't know why it's trying to switch to VFOB when I'm only advertising one VFO, and the command you're running has no reason to touch a second VFO.

I'll see what I can do to reduce the logspam, though.

**Comment by iz4tow** [comment]
It's not only a log issue. Flex device doesn't do the switch to USB/LSB.

**Comment by arodland** [comment]
Okay. Yeah, that's caused by `\get_lock_mode` failing.

Argh, hamlib is so bad at back-compatibility. If an old server doesn't have `\get_lock_mode`, that means that it's always *unlocked* (because the locking feature didn't even exist), but hamlib sees that it doesn't get an expected response to the command, and decides that it's always *locked*, so it refuses to set the mode.

Anyway, fix incoming, and thank you for the info.

**Comment by arodland** [comment]
Please check https://github.com/kc2g-flex-tools/nCAT/releases/tag/v0.1-20221109.1 when you get a chance.

**Comment by iz4tow** [comment]
Tomorrow I'll try and I let you know.
Thank you very much for your effort.
Stupid question: does nDAX have the same issue?

**Comment by arodland** [comment]
nDAX doesn't involve hamlib so no.

**Comment by iz4tow** [comment]
Ok [v0.1-20221109.1](https://github.com/kc2g-flex-tools/nCAT/releases/tag/v0.1-20221109.1) seems to work very well.
If I find out more issues I'll let you know

**Comment by arodland** [comment]
Thanks!
