### ISSUE TITLE
nDAX & nCAT issue

### ISSUE THREAD

**Issue by iz4tow** [kc2g-flex-tools/nCAT#14]
Hi,
I'm trying to use the same Flex 6400 in this way:
- PC 1 -> nCAT and audio from jack   (command to start nCAT: `nCAT -headless -listen 127.0.0.1:4532`)
- PC 2 -> nDAX for audio input. (command to start nDAX: `nDAX -tx false -source virtual_sink -rt false`)

but it seems that when nDAX started nCAT failed, can't I use both on separate PC? And if I try on the same machine will I find the same issue?

Thanks in advance

**Comment by jeremymturner** [comment]
When `nCAT -headless` runs, it should generate a client or station name. I think you'd want to use that when `nDAX` connects.

**Comment by arodland** [comment]
@iz4tow generally that should work. Can you provide any more information on "nCAT failed"?

@jeremymturner nCAT's default station name is the same as nDAX's, so if you don't specify either, they should talk to each other (unless there's another connected station named `Flex`, which is possible of course).

**Comment by iz4tow** [comment]
I tried and I discovered that the issue is not related to nCAT or nDAX
