### ISSUE TITLE
bug on change mode

### ISSUE THREAD

**Issue by iz4tow** [kc2g-flex-tools/nCAT#17]
Good evening, 
I think I encountered a bug in nCAT

FLEX 6400M firmware version 3.7.4
Hamlib: last available today

command:
`rigctl -m2 M USB 3000`
output:
```
set_mode: error = read_string_generic(): RX 2 characters, direct=1
vfo_fixup:(from rig_set_mode:2496) vfo=VFOA, vfo_curr=VFOA, split=0
 rig.c(2520) trace
netrigctl_set_mode called, vfo=VFOA
netrigctl_vfostr: called vfo=VFOA
netrigctl_vfostr: vfo_opt=0
netrigctl_transaction: called len=11
network_flush called
write_block(): TX 11 bytes, method=2
read_string_generic called, rxmax=1024 direct=1, expected_len=1
read_string_generic(): RX 7 characters, direct=1
rig_set_mode: targetable retcode after set_mode(USB)=-8
Protocol error

 2:rig_set_mode: elapsed=79ms
 2:rig.c(2579):rig_set_mode returning(-8) Protocol error

rigctl_parse.c(2257):rigctl_set_mode returning2(-8) Protocol error

Protocol error
```

**Comment by arodland** [comment]
Actually this is a Flex bug (ticket SMART-10100). I think it will be fixed in 3.8.

But it's inconvenient so I will add a workaround in nCAT if I have the time. Thank you for the report.

**Comment by iz4tow** [comment]
Thank you for your quick support and great work!

**Comment by arodland** [comment]
By the way, the bug is only that the command reports failure -- the mode and bandwidth do actually change.
